# Generated by Django 4.0.4 on 2022-04-15 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_uuid', models.UUIDField(unique=True)),
                ('status', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_input_int', models.IntegerField(default=1)),
                ('result', models.JSONField(default=dict)),
            ],
        ),
    ]
